---
title: Dress for the Weather
hero_image: images/banner.png
description: A resource to use the OpenWeatherMap API
original_url: https://raspberrypi.org/learning/dress-for-the-weather
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: weather
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Dress for the weather
- title: Getting it all ready
- title: Getting a city list
- title: Understanding JSON
- title: Getting the city ID
- title: Getting a 5-day forecast in your browser
- title: Getting a 5-day forecast with Python
- title: Looking at the data
- title: Dress for the weather
- title: Getting the arrival date and time
- title: Retrieving the forecast for the required date and time
- title: Testing so far
- title: Making the forecast readable
- title: Testing and understanding the data
- title: Choosing what to wear
- title: Finishing off
- title: What next?